@section('css_datatable')
{!!qcss('public/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css')!!}
{!!qcss('public/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css')!!}
{!!qcss('public/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css')!!}
{!!qcss('public/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css')!!}
{!!qcss('public/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css')!!}
@endsection
@section('js_datatable')
{!!qjs('public/vendors/datatables.net/js/jquery.dataTables.min.js')!!}
{!!qjs('public/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js')!!}
{!!qjs('public/vendors/datatables.net-buttons/js/dataTables.buttons.min.js')!!}
{!!qjs('public/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js')!!}
{!!qjs('public/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js')!!}
{!!qjs('public/vendors/datatables.net-scroller/js/dataTables.scroller.min.js')!!}
{!!qjs('public/vendors/datatables.net-buttons/js/buttons.flash.min.js')!!}
{!!qjs('public/vendors/datatables.net-buttons/js/buttons.html5.min.js')!!}
{!!qjs('public/vendors/datatables.net-buttons/js/buttons.print.min.js')!!}
{!!qjs('public/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js')!!}
{!!qjs('public/vendors/datatables.net-responsive/js/dataTables.responsive.min.js')!!}
{!!qjs('public/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js')!!}
{!!qjs('public/js/datatable_helper.js')!!}
@endsection